{
 "title": "One",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "30s",
 "panels": [
  {
   "title": "RAM% In use:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU% in use:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - avg(rate(node_cpu_seconds_total{mode=\"idle\"}[1m])) by (instance))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk% occupied:",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "100 * (1 - (node_filesystem_avail_bytes{fstype!~\"tmpfs|overlay\"} / node_filesystem_size_bytes{fstype!~\"tmpfs|overlay\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "expr": "{job=\"varlogs\", filename!=\"/var/log/syslog\"} |~ `(?i)` != `debug`"
    }
   ]
  },
  {
   "title": "Panel Title",
   "type": "logs",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 32 },
   "targets": [
    {
     "expr": "{job=\"varlogs\", filename=\"/var/log/auth.log\"} |~ `(?i)failed password` | regexp `(?P<ip>\\d+\\.\\d+\\.\\d+\\.\\d+)` | line_format `{{ .ip }}`"
    }
   ]
  }
 ]
}